# Generated by Django 4.1.7 on 2023-04-27 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_alter_userprofile_pincode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='line1',
            new_name='Address',
        ),
    ]
